name: Create Zip Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 📦 Generate .zip
        uses: byteever/action-build-zip@master
        with:
          filename: 'DelBuonoPaolini_Alberto_Esercizi.zip'

      - name: 🚀 Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: DelBuonoPaolini_Alberto_Esercizi
          path: DelBuonoPaolini_Alberto_Esercizi.zip
