name: Create and Upload Zip Package

on:
  push:
    branches:
      - main
      
jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        
      - name: 📦 Generate .zip
        run: |
          find . -type d \( -name .git -o -name .github \) -prune -o -type f -print | xargs zip DelBuonoPaolini_Alberto_Esercizi.zip

      - name: ⬆ Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: DelBuonoPaolini_Alberto_Esercizi
          path: DelBuonoPaolini_Alberto_Esercizi.zip
