name: Create and Upload Zip Package

on:
  push:
    branches:
      - main
      
jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        
      - name: 🚀 Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: DelBuonoPaolini_Alberto_Esercizi
          path: |
            scripts/*
            latex/*
            esercizio.ipynb
